name: CI testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run-ci-testing:
    runs-on: self-hosted
    env:
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_SSLMODE: ${{ secrets.DB_SSLMODE }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Go
        run: go version
      - name: Start containers
        run: docker compose up -d
      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL..."
          until docker exec postgres-db pg_isready -U "$DB_USER" -d "$DB_NAME"; do
            sleep 2
          done
          echo "Ready"
      - name: Build
        run: go build -v ./...
      - name: Run tests
        run: go test -v ./...
