name: CI testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run-ci-testing:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Go
        run: go version

      - name: Create .env from secrets
        shell: powershell
        run: |
          "@
          SERVER_PORT=${{ secrets.SERVER_PORT }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_SSLMODE=${{ secrets.DB_SSLMODE }}
          JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
          "@ | Out-File -FilePath .env -Encoding utf8

      - name: Start containers
        run: docker compose up -d

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL..."
          until docker exec postgres-db pg_isready -U "$DB_USER" -d "$DB_NAME"; do
            sleep 2
          done
          echo "PostgreSQL is ready"

      - name: Build Go application
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...
