name: CI testing

on:
  push:
    branches: [main, refactor/cicd, production]
  pull_request:
    branches: [main]

jobs:
  run-ci-testing:
    runs-on: self-hosted

    env:
      DATABASE_URL: postgres://postgres:566493@localhost:5432/file_sharing_test?sslmode=disable&options=-csearch_path=test_schema

    steps:
      - uses: actions/checkout@v4

      - name: Check Go
        run: go version

      - name: Decrypt .env
        run: |
          echo "Decrypting..."
          sops --decrypt --input-type dotenv --output-type dotenv --output .env dev.enc
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

      - name: Prepare test database
        shell: powershell
        run: |
          psql -U postgres -h localhost -p 5432 -c "DROP DATABASE IF EXISTS file_sharing_test;"
          psql -U postgres -h localhost -p 5432 -c "CREATE DATABASE file_sharing_test;"
        env:
          PGPASSWORD: 556493
      ##This should be on CD test, not here
      - name: Run tests
        run: go test -v ./test

      - name: Cleanup database
        if: always()
        shell: powershell
        run: |
          psql -U postgres -h localhost -p 5432 -c "DROP DATABASE IF EXISTS file_sharing_test;"
        env:
          PGPASSWORD: 556493
