name: CI testing

on:
  push:
    branches: [main, refactor/cicd, production]
  pull_request:
    branches: [main]

jobs:
  run-ci-testing:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Check Go
        run: go version

      - name: Decrypt .env
        run: |
          echo "Decrypting..."
          sops --decrypt --input-type dotenv --output-type dotenv --output .env dev.enc
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

      - name: Cleanup old containers & volumes
        run: docker compose down -v

      - name: Build & start containers
        run: docker compose up -d --build

      - name: Run tests
        run: go test -v ./test